#include "library.h"

int main(int argc, char **argv)
{

    decode("EC ED EE EF FA FB FC FD FE FF");
    return 0;
}

/*  THE NEXT CIPHER IS COMPLETELY OFF THE RAILS!
    WHEN YOU WRITE OUT THE SOLUTION,
    IT LOOKS LIKE A WAVE OR A ZIGZAG.
    THESE TYPES OF CIPHERS ARE USUALLY CALLED
    TRANSPOSITION CIPHERS.
    IT IS NOT STRONG, BUT DEFINITELY FUN.

    TO SOLVE THIS CIPHER YOU WILL NEED THE
    NUMBER KEY 4.
    CONSIDER SPACES, COMMAS, PERIODS, AND OTHER
    PUNCTUATION ALSO AS CHARACTERS.
    BINARY FOR THIS TASK MUST BE CALLED "RAILFENCE".
    AND AS ALWAYS, THE PROGRAM HAS TO HAVE THE SAME
    ERROR HANDLING RULES AS THE PREVIOUS ONES
    EXCEPT THE BINARY NAME.
 */
